language: python
dist: xenial
sudo: required

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

# command to install dependencies
install:
  - pip install pytest mock

# command to run tests
script: py.test -v

jobs:
  include:
    - stage: Kodi-Addon-Check
      python: 3.6

      # command to install dependencies
      install:
        - pip install kodi-addon-checker
      # command to run tests
      script:
        - kodi-addon-checker --branch=leia  -- service.notrobro/;
